"use client";
import { FormEvent, useState } from "react";
import { analyzeResume, uploadResume, type AnalyzeResumeResult, type UploadResumeResult } from "@/lib/resumes";

export function ResumeAts({ applicationId, initialJobDescription }: { applicationId: string; initialJobDescription: string | null }) {
  const [upload, setUpload] = useState<UploadResumeResult["data"] | null>(null); const [analysis, setAnalysis] = useState<AnalyzeResumeResult["data"] | null>(null); const [jobDescription, setJobDescription] = useState(initialJobDescription ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function onUpload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const file = new FormData(event.currentTarget).get("resume"); if (!(file instanceof File) || !file.name) { setError("Choose a PDF or DOCX resume."); return; } setBusy(true); try { const result = await uploadResume(applicationId, file); setUpload(result.data); setAnalysis(null); } catch (e) { setError(e instanceof Error ? e.message : "Unable to upload resume."); } finally { setBusy(false); } }
  async function onAnalyze(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!upload) return; setError(""); setBusy(true); try { const result = await analyzeResume(applicationId, upload.resume_id, jobDescription); setAnalysis(result.data); } catch (e) { setError(e instanceof Error ? e.message : "Unable to calculate ATS score."); } finally { setBusy(false); } }
  return <section className="mt-8 rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Resume & ATS</h2><p className="mt-1 text-sm text-slate-500">Upload a PDF or DOCX to extract career details and calculate an ATS score for this role.</p><form className="mt-5 flex flex-wrap items-center gap-3" onSubmit={onUpload}><input name="resume" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="text-sm" /><button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Working…" : "Upload resume"}</button></form>{upload && <div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm"><p className="font-medium">Resume details extracted</p><p className="mt-2 text-slate-600">{upload.parsed_data.experience_years} years experience · {upload.parsed_data.skills.join(", ") || "No recognized skills"}</p></div>}{upload && <form className="mt-5 space-y-3" onSubmit={onAnalyze}><label className="block text-sm font-medium">Job description<textarea value={jobDescription} onChange={e => setJobDescription(e.target.value)} required className="mt-1.5 min-h-32 w-full rounded-lg border border-slate-300 p-3" /></label><button disabled={busy} className="rounded-lg border border-indigo-600 px-4 py-2 text-sm font-semibold text-indigo-700 disabled:opacity-60">{busy ? "Working…" : "Calculate ATS score"}</button></form>}{analysis && <div className="mt-5 rounded-lg bg-emerald-50 p-4"><p className="text-sm font-medium text-emerald-800">ATS score: {analysis.ats_score}/100</p><p className="mt-1 text-sm text-emerald-800">{analysis.jd_details.role_title || "Job description"} · Required skills: {analysis.jd_details.required_skills.join(", ") || "None recognized"}</p></div>}{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</section>;
}
